#pragma once

#include <iostream>
#include <windows.h>
#include <string>
#include <TlHelp32.h>

#include "cheatFuncs.hpp"

struct cInfo {
	HANDLE hProcess;
	uintptr_t baseAddress;
	DWORD PlayerPTR;
};

extern cInfo* INFO;

#define GEOMETRY_TOUCH_OFFSET 0x20A23C
#define GEOMETRY_MUSIC_HACK_OFFSET 0x3222E4
#define GEOMETRY_JUMP_OFFSET 0x1E9498

#define GEOMETRY_PRACTICE_MUSIC_OFFSET_1 0x20C925
#define GEOMETRY_PRACTICE_MUSIC_OFFSET_2 0x20D143
#define GEOMETRY_PRACTICE_MUSIC_OFFSET_3 0x20A563
#define GEOMETRY_PRACTICE_MUSIC_OFFSET_4 0x20A595

#define GEOMETRY_ICONS_OFFSET 0xC50A8
#define GEOMETRY_PLAYER_PTR_OFFSET INFO->baseAddress + 0x3222D0

#define GEOMETRY_PLAYER_NAME_LENGHT_OFFSET 0x1A8
#define GEOMETRY_PLAYER_NAME_OFFSET 0x198

#define GEOMETRY_UNLOCK_LEVELS_OFFSET 0x188CE1

#define GEOMETRY_SHOPHACK_1_OFFSET 0xF33BB
#define GEOMETRY_SHOPHACK_2_OFFSET 0x14B339

#define GEOMETRY_SECRET_LVL_OFFSET 0x2214E0

// The anticheat system (lol)
#define GEOMETRY_PATCH_SPEEDHACK_AC 0x202AAA
#define GEOMETRY_PATCH_RESET_AC 0x20C4E6
#define GEOMETRY_PATCH_LOAD_LEVEL_AC 0x18B2B4

#define GEOMETRY_PATCH_LEVEL_KICK_AC 0x20D3B3
#define GEOMETRY_PATCH_LEVEL_KICK_AC_1 0x1FF7A2

#define GEOMETRY_PATCH_LEVEL_COMP_AC 0x1FD557
#define GEOMETRY_PATCH_LEVEL_COMP_AC_2 0x1FD742
#define GEOMETRY_PATCH_LEVEL_COMP_AC_3 0x1FD756
#define GEOMETRY_PATCH_LEVEL_COMP_AC_4 0x1FD79A
#define GEOMETRY_PATCH_LEVEL_COMP_AC_5 0x1FD7AF

#define GEOMETRY_PATCH_EDITOR_AC 0x15FC2E